---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dr-cloudproducercmorders
  namespace: confluent
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: dr-cloudproducercmorders
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: dr-cloudproducercmorders
  template:
    metadata:
      labels:
        app: dr-cloudproducercmorders
    spec:
      containers:
      - name: dr-cloudproducercmorders
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          for x in {1..1000}; do echo "{"number":$x,"date":18500$x,"shipping_address":"shipping street $x, $x Shipping-City, Global","cost":$x}"; sleep 2; done | kafka-console-producer --bootstrap-server  $(awk '/bootstrap.servers=/{print $NF}' /mnt/dr-kafkatools_producer.properties | cut -d'=' -f 2) --topic cmorders --producer.config /mnt/dr-kafkatools_producer.properties      
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties 
          secret:
            secretName: dr-kafka-client-producer-config-secure
---
apiVersion: v1
kind: Service
metadata:
  name: dr-cloudproducercmorders
  namespace: confluent
spec:
  clusterIP: None