---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prod-cloudproducercmcustomers
  namespace: confluent
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: prod-cloudproducercmcustomers
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: prod-cloudproducercmcustomers
  template:
    metadata:
      labels:
        app: prod-cloudproducercmcustomers
    spec:
      containers:
      - name: prod-cloudproducercmcustomers
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          for x in {1..1000}; do echo "{"custid":$x,"Name":"Name-$x","Address":"Street $x, $x Customer-City, Global"}"; sleep 2; done | kafka-console-producer --bootstrap-server  $(awk '/bootstrap.servers=/{print $NF}' /mnt/kafkatools_producer.properties | cut -d'=' -f 2) --topic cmcustomers --producer.config /mnt/kafkatools_producer.properties      
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties # Create secret with name `kafka-client-config` with client configurations
          secret:
            secretName: dr-kafka-client-producer-config-secure
---
apiVersion: v1
kind: Service
metadata:
  name: prod-cloudproducercmcustomers
  namespace: confluent
spec:
  clusterIP: None